"""CloudFormation custom resource — bootstrap the Cognito service user.

Triggered by `Custom::ServiceUser` in the SAM template. On Create/Update:
  1. Read the service-user password from Secrets Manager (auto-generated by
     SAM via `GenerateSecretString`).
  2. Create the user in Cognito (idempotent — ignore "already exists").
  3. Set the password as permanent (skip the FORCE_CHANGE_PASSWORD flow).

On Delete: best-effort delete the user (so the Cognito pool can be torn down).

Sends success/failure to the CFN response URL via `urllib`. We deliberately
avoid the cfnresponse package because it isn't always preinstalled.
"""

from __future__ import annotations

import json
import os
import urllib.request
from typing import Any

import boto3
from botocore.exceptions import ClientError


def _send(event: dict[str, Any], status: str, data: dict[str, Any] | None = None,
          reason: str = "") -> None:
    body = {
        "Status": status,
        "Reason": reason or f"See CloudWatch logs for {event.get('LogicalResourceId')}",
        "PhysicalResourceId": event.get("PhysicalResourceId") or event.get("LogicalResourceId", "service-user"),
        "StackId": event["StackId"],
        "RequestId": event["RequestId"],
        "LogicalResourceId": event["LogicalResourceId"],
        "Data": data or {},
    }
    raw = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(
        url=event["ResponseURL"],
        data=raw,
        headers={"content-type": "", "content-length": str(len(raw))},
        method="PUT",
    )
    urllib.request.urlopen(req).read()  # noqa: S310 - URL is from CFN


def _get_password(secret_arn: str) -> str:
    sm = boto3.client("secretsmanager")
    resp = sm.get_secret_value(SecretId=secret_arn)
    return resp["SecretString"]


def _create_or_update(user_pool_id: str, email: str, password: str) -> None:
    cog = boto3.client("cognito-idp")
    try:
        cog.admin_create_user(
            UserPoolId=user_pool_id,
            Username=email,
            UserAttributes=[
                {"Name": "email", "Value": email},
                {"Name": "email_verified", "Value": "true"},
            ],
            MessageAction="SUPPRESS",
        )
    except ClientError as e:
        if e.response["Error"]["Code"] != "UsernameExistsException":
            raise
    # Always (re)set the password so a stack update with a rotated secret picks up.
    cog.admin_set_user_password(
        UserPoolId=user_pool_id,
        Username=email,
        Password=password,
        Permanent=True,
    )


def _delete(user_pool_id: str, email: str) -> None:
    cog = boto3.client("cognito-idp")
    try:
        cog.admin_delete_user(UserPoolId=user_pool_id, Username=email)
    except ClientError as e:
        # User pool itself may already be torn down — ignore.
        if e.response["Error"]["Code"] not in {"UserNotFoundException", "ResourceNotFoundException"}:
            raise


def handler(event: dict[str, Any], _context: Any) -> None:
    request_type = event["RequestType"]
    props = event.get("ResourceProperties") or {}
    user_pool_id = props.get("UserPoolId") or os.environ["USER_POOL_ID"]
    email = props.get("Email") or os.environ.get("SERVICE_USER_EMAIL", "service-local-monitor@workq.internal")
    secret_arn = props.get("SecretArn") or os.environ["SECRET_ARN"]

    try:
        if request_type in ("Create", "Update"):
            password = _get_password(secret_arn)
            _create_or_update(user_pool_id, email, password)
            _send(event, "SUCCESS", {"Email": email})
        elif request_type == "Delete":
            _delete(user_pool_id, email)
            _send(event, "SUCCESS", {})
        else:
            _send(event, "FAILED", reason=f"unknown RequestType {request_type}")
    except Exception as e:  # noqa: BLE001
        _send(event, "FAILED", reason=str(e))
        raise
